version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dbcenter
    environment:
      MYSQL_ROOT_PASSWORD: @Wad235rt
      MYSQL_DATABASE: dbcenter
      MYSQL_USER: admin
      MYSQL_PASSWORD: @Wad235rt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: